システム開発ガイドより、プロジェクト固有とする必要がない差分内容を反映
nablarch-development-standards/nablarch-development-standards pull request #43
Opened 2024-07-26 09:44 UTC by tisuchida

ファイルごとに、以下の差分内容を取り込みました。

- UI標準(画面).xlsx
  - 3.2.1.2. 補足説明
    - 「検索条件入力画面」の説明で、以下追加
      検索結果が0件の場合、検索条件入力画面内でユーザにエラー通知する。
    - 「検索結果一覧画面」の説明で、以下追加
      詳細画面から戻る際に、前回の検索条件を復元して再検索を行う。
    - 「詳細画面」の説明で、以下追加
      初期表示の検索結果が0件の場合、共通エラー画面を表示する。
  - 3.2.4. 「検索(検索一覧) → 単一更新・削除」型
    - システム開発ガイドの内容で置換
  - 3.2.5.2. 補足説明
    - 「検索結果一覧更新/削除画面」の説明で、以下追加
      検索結果はページングできるようにする。
  - 3.4. エラー時の画面遷移
    - 「各画面遷移と、該当するエラーの種類を以下に示す。」以下の表の欄外に、以下追加
      ※排他制御エラーについて、本システムではデータの同時更新が頻繁に発生することは想定されないため、
      　元画面への遷移は行わなず共通エラー画面への遷移で対処することとする。
  - 5.5.3. 戻る機能への対応方針
    - ブラウザバックの方針を「許容」から「動作保証対象外」に変更
      
- 各単体テスト仕様書フォーマット
  - 「【テストターゲット名】クラス単体」シート名を「【リクエストID】クラス単体テスト」に変更
  - 「【リクエストID】リクエスト単体」シート名を「【リクエストID】リクエスト単体テスト」に変更
  - 「【リクエストID】リクエスト単体」シートのヘッダにある「リクエストID」「バッチ処理ID」を削除
  - 各シートのケースNoカラムヘッダに、サンプルの記載に合わせて採番方法のメモを追加

- 単体テスト仕様書(バッチ)_(取引ID)_(取引名).xlsx
  - 取引単体テストのデータバリエーションのテストケースNoを、「2-1-1」から「1-2-1」に変更

- 各単体テスト仕様書サンプル
  - 「【テストターゲット名】クラス単体」シート名を「【リクエストID】クラス単体テスト」に変更
  - 「【リクエストID】リクエスト単体」シート名を「【リクエストID】リクエスト単体テスト」に変更
  - 「【リクエストID】リクエスト単体」シートのヘッダにある「リクエストID」「バッチ処理ID」を削除

2024-07-29 05:53 UTC, tisuchida commented
別途指摘をふまえ、以下の通り修正しました。

- 各単体テスト仕様書フォーマット
  - 「【リクエストID】クラス単体テスト」シート名を「【テストターゲット名】クラス単体に変更
  - 「【リクエストID】リクエスト単体テスト」シート名を「【リクエストID】リクエスト単体」に変更
  - 各リクエスト単体のシートヘッダの「テストターゲット名」の記載を削除し、代わりに「リクエストID」「バッチ処理ID」を追加

- 各単体テスト仕様書サンプル
  - フォーマットでの修正事項を反映
  - 各クラス単体のシート名に、テストターゲットとなるクラス名を記載
  - 各リクエスト単体のシート名に、リクエストIDを記載


664bece4cde3259f4ae05f538846349d03b9ccd9

2024-07-31 05:41 UTC, kumagoro1202 requested changes

2024-07-31 05:41 UTC, kumagoro1202 commented on 030_設計ドキュメント/010_フォーマット/110_テスト仕様書/単体テスト仕様書(画面)_(取引ID)_(取引名).xlsx
リクエスト単体テストのヘッダーについて
口頭で会話した際にシステム開発ガイドと合わせればいいという話にはなりましたが、どう合わせるかは具体的に話せていなかったかと思います。
現在はリクエストIDを削除してシステム開発ガイドに合わせようとしてくれていますが、開発標準が対象とするシステムにおいてはリクエスト単体テストはリクエストID単位にシートを作成するものだと思います。（サンプルのリクエスト単体テストシートの上部オブジェクトにも書かれています。）リクエストIDは残し、システム開発ガイド側のフォーマットにリクエストIDを追加した上で、サンプルプロジェクトにおいては画面単位でリクエスト単体テストを行うため不要とかのコメントをしたほうが良いと思います。
↓この2つの修正は元に戻して欲しいです。
- 「【リクエストID】リクエスト単体」シート名を「【テストターゲット名】リクエスト単体」に変更
- 「【テストターゲット名】リクエスト単体」シートのヘッダにある「リクエストID」「バッチ処理ID」を「テストターゲット名」に変更

2024-08-01 04:34 UTC, tisuchida commented on 030_設計ドキュメント/010_フォーマット/110_テスト仕様書/単体テスト仕様書(画面)_(取引ID)_(取引名).xlsx
質問が2点あります。
1. 別途指摘で、サンプルプロジェクトの画面の単体テスト仕様書については、シート名に画面のIDが記載されることを踏まえてフォーマット側のシート名を「【画面ID】_リクエスト単体」とすればよいとなったと思います。これに合わせて、ヘッダ部分も「リクエストID」を「画面ID」とするのが良いように思いますがいかがでしょうか。
2. サンプルプロジェクトの単体テスト仕様書は、Webサービスのものもあります。Webサービスのものについては、「リクエストID」に相当するものが「API ID」と設計書に記載されていますが、これも「API ID」としてしまってよいでしょうか。

2024-08-01 04:42 UTC, kumagoro1202 commented on 030_設計ドキュメント/010_フォーマット/110_テスト仕様書/単体テスト仕様書(画面)_(取引ID)_(取引名).xlsx
1.  システム開発ガイドのサンプルプロジェクトはNTFを使わない前提なのでシートの単位が画面単位になるので画面IDにするという話になりました。対して開発標準はNTFを前提としているのでシートはリクエスト単位にします。そのためリクエストIDは変更しないでください。
2. 単体テスト仕様書はNTFとのひも付きが強いのでリクエストIDにしましょう。バッチ処理IDもリクエストIDにして単体テスト仕様書上では実行基盤に関わらずリクエストIDの呼称を使いましょう。

2024-08-01 07:27 UTC, tisuchida commented on 030_設計ドキュメント/010_フォーマット/110_テスト仕様書/単体テスト仕様書(画面)_(取引ID)_(取引名).xlsx
以下の修正を実施しました。

- フォーマット
  - リクエスト単体のシート名を、「【テストターゲット名】リクエスト単体」から「【リクエストID】リクエスト単体」に戻しました。
  - リクエスト単体シートのヘッダの「テストターゲット名」の1行下に「リクエストID」を追加しました。
  - バッチのリクエスト単体については、「バッチ処理ID」の記載を「リクエストID」に修正しました。
- サンプル
  - フォーマットの修正を取り込みました。

2024-08-02 05:48 UTC, kumagoro1202 approved these changes

2024-08-02 05:51 UTC, merged